#.....secrets.toml
SUPABASE_URL=https://vmrsgrvtiympwrkultwm.supabase.co
SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtcnNncnZ0aXltcHdya3VsdHdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxOTE5MjcsImV4cCI6MjA2MDc2NzkyN30.1VdfHrDUPj9qeHdVJmTlN6XX5emg0zcyoyQfu06dM40
OPENAI_API_KEY=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
