SUPABASE_URL="https://vmrsgrvtiympwrkultwm.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtcnNncnZ0aXltcHdya3VsdHdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxOTE5MjcsImV4cCI6MjA2MDc2NzkyN30.1VdfHrDUPj9qeHdVJmTlN6XX5emg0zcyoyQfu06dM40"
OPENAI_API_KEY="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"
