SUPABASE_URL="https://vmrsgrvtiympwrkultwm.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtcnNncnZ0aXltcHdya3VsdHdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxOTE5MjcsImV4cCI6MjA2MDc2NzkyN30.1VdfHrDUPj9qeHdVJmTlN6XX5emg0zcyoyQfu06dM40"
OPENAI_API_KEY="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"
